// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logic$0 from "../../core/logic/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} urlPass
 * @param {string} pass
 * @param {string} postField
 * @param {string} command
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function ExecCommandWithMd5Horse(urlPass, pass, postField, command) {
    return $Call.ByID(1506217965, urlPass, pass, postField, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} command
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function ExecCommandWithShell(command) {
    return $Call.ByID(2196525974, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} command
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function ExecCommandWithUndeadHorse(command) {
    return $Call.ByID(2309319658, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} urlPass
 * @param {string} pass
 * @param {string} command
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function ExecCommandWithWormShell(urlPass, pass, command) {
    return $Call.ByID(1133136971, urlPass, pass, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<{ [_: string]: any }>}
 */
export function GetShellTestStatus() {
    return $Call.ByID(3323634814).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<logic$0.TaskState | null>}
 */
export function GetTaskStatus(taskID) {
    return $Call.ByID(2071743349, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTargets() {
    return $Call.ByID(75729668).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string[]} targets
 * @returns {$CancellablePromise<void>}
 */
export function SaveTargets(targets) {
    return $Call.ByID(3685971107, targets);
}

/**
 * @param {$models.EventEmitter} emitter
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emitter) {
    return $Call.ByID(2514650252, emitter);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function TestShell() {
    return $Call.ByID(2292597956);
}

/**
 * @param {string[]} targets
 * @returns {$CancellablePromise<string>}
 */
export function TestShellWithTargets(targets) {
    return $Call.ByID(3339175778, targets);
}

/**
 * @param {string} pass
 * @param {string} postField
 * @param {string} $2
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function UploadMd5Horse(pass, postField, $2) {
    return $Call.ByID(1539758538, pass, postField, $2).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} urlPass
 * @param {string} pass
 * @param {string} $2
 * @returns {$CancellablePromise<string>}
 */
export function UploadUndeadHorse(urlPass, pass, $2) {
    return $Call.ByID(2921179931, urlPass, pass, $2);
}

/**
 * @param {string} urlPass
 * @param {string} pass
 * @returns {$CancellablePromise<logic$0.CommandResult[]>}
 */
export function UploadWormShell(urlPass, pass) {
    return $Call.ByID(2010564498, urlPass, pass).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = logic$0.CommandResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = logic$0.TaskState.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
