// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(3363716930).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function LoadConfig() {
    return $Call.ByID(2362897554).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig() {
    return $Call.ByID(2707778295);
}

/**
 * @param {string} host
 * @param {string} port
 * @param {string} username
 * @param {string} password
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDatabaseConfig(host, port, username, password, name) {
    return $Call.ByID(360434386, host, port, username, password, name);
}

/**
 * @param {string} ownIPs
 * @returns {$CancellablePromise<void>}
 */
export function UpdateOwnIPs(ownIPs) {
    return $Call.ByID(3354052907, ownIPs);
}

/**
 * @param {string} host
 * @param {string} port
 * @param {string} username
 * @param {string} password
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSSHConfig(host, port, username, password, path) {
    return $Call.ByID(990235103, host, port, username, password, path);
}

/**
 * @param {string} port
 * @param {string} pass
 * @param {string} path
 * @param {string} file
 * @param {string} method
 * @param {string} query
 * @param {string} payload
 * @returns {$CancellablePromise<void>}
 */
export function UpdateShellConfig(port, pass, path, file, method, query, payload) {
    return $Call.ByID(2457017991, port, pass, path, file, method, query, payload);
}

/**
 * @param {string} proxy
 * @returns {$CancellablePromise<void>}
 */
export function UpdateShellProxy(proxy) {
    return $Call.ByID(3548465179, proxy);
}

/**
 * @param {string} urlPass
 * @param {string} pass
 * @param {string} filename
 * @returns {$CancellablePromise<void>}
 */
export function UpdateUndeadConfig(urlPass, pass, filename) {
    return $Call.ByID(2583009866, urlPass, pass, filename);
}

/**
 * @param {string} urlPass
 * @param {string} pass
 * @returns {$CancellablePromise<void>}
 */
export function UpdateWormConfig(urlPass, pass) {
    return $Call.ByID(3466429112, urlPass, pass);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
