// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logic$0 from "../../core/logic/models.js";

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function BackupDatabase(targetsInput) {
    return $Call.ByID(3075044495, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function BackupWebRoot(targetsInput) {
    return $Call.ByID(3320581060, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @param {string} password
 * @returns {$CancellablePromise<string[]>}
 */
export function ChangeDatabasePassword(targetsInput, password) {
    return $Call.ByID(2012696284, targetsInput, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function DeploySimpleWAF(targetsInput) {
    return $Call.ByID(2431226873, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<logic$0.ShellFinding[]>}
 */
export function FindShells(targetsInput) {
    return $Call.ByID(1615914544, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function HardenPHPConfig(targetsInput) {
    return $Call.ByID(91659444, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function HardenWebRoot(targetsInput) {
    return $Call.ByID(692345048, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function InspectHost(targetsInput) {
    return $Call.ByID(1615731170, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @returns {$CancellablePromise<string[]>}
 */
export function MakeUploadDirsReadOnly(targetsInput) {
    return $Call.ByID(4162864561, targetsInput).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @param {string} path
 * @returns {$CancellablePromise<string[]>}
 */
export function RestoreDatabaseFromBackup(targetsInput, path) {
    return $Call.ByID(1951334173, targetsInput, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} targetsInput
 * @param {string} path
 * @returns {$CancellablePromise<string[]>}
 */
export function RestoreWebFromBackup(targetsInput, path) {
    return $Call.ByID(54607662, targetsInput, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = logic$0.ShellFinding.createFrom;
const $$createType2 = $Create.Array($$createType1);
