// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function ListOutputFiles() {
    return $Call.ByID(3425667076).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ReadLogFile() {
    return $Call.ByID(4202985572);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ReadOutputFile(name) {
    return $Call.ByID(4206127819, name);
}

/**
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveOutputFile(name, content) {
    return $Call.ByID(2355802134, name, content);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
