// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logic$0 from "../../core/logic/models.js";

/**
 * @param {string} pathTemplate
 * @returns {$CancellablePromise<logic$0.FlagResult[]>}
 */
export function FetchFlagsAndSave(pathTemplate) {
    return $Call.ByID(3791975129, pathTemplate).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} pathTemplate
 * @param {string} shellType
 * @param {string} urlPass
 * @param {string} pass
 * @param {string} postField
 * @param {string} command
 * @returns {$CancellablePromise<logic$0.FlagResult[]>}
 */
export function FetchFlagsAndSaveWithShell(pathTemplate, shellType, urlPass, pass, postField, command) {
    return $Call.ByID(118990345, pathTemplate, shellType, urlPass, pass, postField, command).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = logic$0.FlagResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
