// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logic$0 from "../../core/logic/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pcapsearch$0 from "../../pcapsearch/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pcapstore$0 from "../../pcapstore/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<logic$0.RemoteTrafficRecord[]>}
 */
export function GetCaptureHistory(query, limit) {
    return $Call.ByID(2224296256, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @returns {$CancellablePromise<pcapstore$0.PcapDetail | null>}
 */
export function GetPcapDetail(id) {
    return $Call.ByID(3797840007, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<logic$0.RemoteCaptureState | null>}
 */
export function GetRemoteCaptureState() {
    return $Call.ByID(4012195799).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} query
 * @param {number} page
 * @param {number} size
 * @returns {$CancellablePromise<pcapsearch$0.SearchResult[]>}
 */
export function SearchTraffic(query, page, size) {
    return $Call.ByID(3203247531, query, page, size).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {$models.EventEmitter} emitter
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emitter) {
    return $Call.ByID(960761776, emitter);
}

/**
 * @param {logic$0.RemoteCaptureRequest} request
 * @returns {$CancellablePromise<logic$0.RemoteCaptureState | null>}
 */
export function StartRemoteCapture(request) {
    return $Call.ByID(2939076446, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<logic$0.RemoteCaptureState | null>}
 */
export function StopRemoteCapture() {
    return $Call.ByID(3226716054).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = logic$0.RemoteTrafficRecord.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = pcapstore$0.PcapDetail.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = logic$0.RemoteCaptureState.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = pcapsearch$0.SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
