// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logic$0 from "../../core/logic/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} targetsInput
 * @param {string} username
 * @param {string} port
 * @param {string[]} oldPasswords
 * @param {string} newPassword
 * @param {number} maxConcurrency
 * @returns {$CancellablePromise<logic$0.SSHPasswordChangeResponse | null>}
 */
export function ChangeSSHPasswords(targetsInput, username, port, oldPasswords, newPassword, maxConcurrency) {
    return $Call.ByID(1455522403, targetsInput, username, port, oldPasswords, newPassword, maxConcurrency).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {logic$0.SSHConnectRequest} request
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function ConnectSSH(request) {
    return $Call.ByID(2706920475, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function CreateRemoteDirectory(remotePath) {
    return $Call.ByID(150139248, remotePath);
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function CreateRemoteFile(remotePath) {
    return $Call.ByID(581787787, remotePath);
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRemoteEntry(remotePath) {
    return $Call.ByID(2969811274, remotePath);
}

/**
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function DisconnectSSH() {
    return $Call.ByID(4153428617).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<logic$0.FileTransferResult | null>}
 */
export function DownloadRemoteFile(remotePath) {
    return $Call.ByID(1387905679, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<logic$0.SmokeReport | null>}
 */
export function GetLatestSmokeReport() {
    return $Call.ByID(1772804933).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function GetSSHConnectionState() {
    return $Call.ByID(1827979626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<logic$0.RemoteFileList | null>}
 */
export function ListRemoteDirectory(remotePath) {
    return $Call.ByID(2078962704, remotePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} remoteDir
 * @returns {$CancellablePromise<logic$0.FileTransferResult[]>}
 */
export function PickAndUploadLocalFiles(remoteDir) {
    return $Call.ByID(4276840240, remoteDir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadRemoteTextFile(remotePath) {
    return $Call.ByID(3934151572, remotePath);
}

/**
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function ReconnectSSH() {
    return $Call.ByID(2578226310).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameRemoteEntry(oldPath, newPath) {
    return $Call.ByID(3075926373, oldPath, newPath);
}

/**
 * @returns {$CancellablePromise<logic$0.SmokeReport | null>}
 */
export function RunIntegrationSmoke() {
    return $Call.ByID(4020218491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} input
 * @returns {$CancellablePromise<void>}
 */
export function SendTerminalInput(input) {
    return $Call.ByID(1647409483, input);
}

/**
 * @param {$models.EventEmitter} emitter
 * @returns {$CancellablePromise<void>}
 */
export function SetEventEmitter(emitter) {
    return $Call.ByID(1187259671, emitter);
}

/**
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function StartTerminal() {
    return $Call.ByID(1285202793).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<logic$0.SSHConnectionState | null>}
 */
export function StopTerminal() {
    return $Call.ByID(2602084675).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} remoteDir
 * @param {string} filename
 * @param {string} contentBase64
 * @returns {$CancellablePromise<logic$0.FileTransferResult | null>}
 */
export function UploadRemoteFileContent(remoteDir, filename, contentBase64) {
    return $Call.ByID(3709160807, remoteDir, filename, contentBase64).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} remotePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteRemoteTextFile(remotePath, content) {
    return $Call.ByID(918363385, remotePath, content);
}

// Private type creation functions
const $$createType0 = logic$0.SSHPasswordChangeResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = logic$0.SSHConnectionState.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = logic$0.FileTransferResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = logic$0.SmokeReport.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = logic$0.RemoteFileList.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType4);
