// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export class CommandResult {
    /**
     * Creates a new CommandResult instance.
     * @param {Partial<CommandResult>} [$$source = {}] - The source object to create the CommandResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult(/** @type {Partial<CommandResult>} */($$parsedSource));
    }
}

export class FileTransferResult {
    /**
     * Creates a new FileTransferResult instance.
     * @param {Partial<FileTransferResult>} [$$source = {}] - The source object to create the FileTransferResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("remotePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remotePath"] = "";
        }
        if (!("localPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localPath"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileTransferResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileTransferResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileTransferResult(/** @type {Partial<FileTransferResult>} */($$parsedSource));
    }
}

export class FlagResult {
    /**
     * Creates a new FlagResult instance.
     * @param {Partial<FlagResult>} [$$source = {}] - The source object to create the FlagResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("flag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["flag"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlagResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlagResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlagResult(/** @type {Partial<FlagResult>} */($$parsedSource));
    }
}

export class RemoteCaptureRequest {
    /**
     * Creates a new RemoteCaptureRequest instance.
     * @param {Partial<RemoteCaptureRequest>} [$$source = {}] - The source object to create the RemoteCaptureRequest.
     */
    constructor($$source = {}) {
        if (!("targetsInput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["targetsInput"] = "";
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("filter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCaptureRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteCaptureRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteCaptureRequest(/** @type {Partial<RemoteCaptureRequest>} */($$parsedSource));
    }
}

export class RemoteCaptureSession {
    /**
     * Creates a new RemoteCaptureSession instance.
     * @param {Partial<RemoteCaptureSession>} [$$source = {}] - The source object to create the RemoteCaptureSession.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (!("lastSeen" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastSeen"] = null;
        }
        if (!("lastLine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastLine"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCaptureSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteCaptureSession}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteCaptureSession(/** @type {Partial<RemoteCaptureSession>} */($$parsedSource));
    }
}

export class RemoteCaptureState {
    /**
     * Creates a new RemoteCaptureState instance.
     * @param {Partial<RemoteCaptureState>} [$$source = {}] - The source object to create the RemoteCaptureState.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (!("interface" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface"] = "";
        }
        if (!("filter" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filter"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {RemoteCaptureSession[]}
             */
            this["sessions"] = [];
        }
        if (!("records" in $$source)) {
            /**
             * @member
             * @type {RemoteTrafficRecord[]}
             */
            this["records"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteCaptureState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteCaptureState}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField4_0($$parsedSource["sessions"]);
        }
        if ("records" in $$parsedSource) {
            $$parsedSource["records"] = $$createField5_0($$parsedSource["records"]);
        }
        return new RemoteCaptureState(/** @type {Partial<RemoteCaptureState>} */($$parsedSource));
    }
}

export class RemoteFileEntry {
    /**
     * Creates a new RemoteFileEntry instance.
     * @param {Partial<RemoteFileEntry>} [$$source = {}] - The source object to create the RemoteFileEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteFileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteFileEntry(/** @type {Partial<RemoteFileEntry>} */($$parsedSource));
    }
}

export class RemoteFileList {
    /**
     * Creates a new RemoteFileList instance.
     * @param {Partial<RemoteFileList>} [$$source = {}] - The source object to create the RemoteFileList.
     */
    constructor($$source = {}) {
        if (!("currentPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentPath"] = "";
        }
        if (!("parentPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentPath"] = "";
        }
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {RemoteFileEntry[]}
             */
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteFileList instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteFileList}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new RemoteFileList(/** @type {Partial<RemoteFileList>} */($$parsedSource));
    }
}

export class RemoteTrafficRecord {
    /**
     * Creates a new RemoteTrafficRecord instance.
     * @param {Partial<RemoteTrafficRecord>} [$$source = {}] - The source object to create the RemoteTrafficRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("srcIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcIp"] = "";
        }
        if (!("dstIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstIp"] = "";
        }
        if (!("srcPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcPort"] = "";
        }
        if (!("dstPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstPort"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("raw" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["raw"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteTrafficRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteTrafficRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteTrafficRecord(/** @type {Partial<RemoteTrafficRecord>} */($$parsedSource));
    }
}

export class SSHConnectRequest {
    /**
     * Creates a new SSHConnectRequest instance.
     * @param {Partial<SSHConnectRequest>} [$$source = {}] - The source object to create the SSHConnectRequest.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectRequest(/** @type {Partial<SSHConnectRequest>} */($$parsedSource));
    }
}

export class SSHConnectionState {
    /**
     * Creates a new SSHConnectionState instance.
     * @param {Partial<SSHConnectionState>} [$$source = {}] - The source object to create the SSHConnectionState.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["connectedAt"] = null;
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }
        if (!("terminalOpen" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["terminalOpen"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectionState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectionState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectionState(/** @type {Partial<SSHConnectionState>} */($$parsedSource));
    }
}

export class SSHPasswordChangeResponse {
    /**
     * Creates a new SSHPasswordChangeResponse instance.
     * @param {Partial<SSHPasswordChangeResponse>} [$$source = {}] - The source object to create the SSHPasswordChangeResponse.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {SSHPasswordChangeResult[]}
             */
            this["results"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success"] = 0;
        }
        if (!("authFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["authFailed"] = 0;
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["error"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHPasswordChangeResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHPasswordChangeResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SSHPasswordChangeResponse(/** @type {Partial<SSHPasswordChangeResponse>} */($$parsedSource));
    }
}

export class SSHPasswordChangeResult {
    /**
     * Creates a new SSHPasswordChangeResult instance.
     * @param {Partial<SSHPasswordChangeResult>} [$$source = {}] - The source object to create the SSHPasswordChangeResult.
     */
    constructor($$source = {}) {
        if (!("ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip"] = "";
        }
        if (!("usedPassword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["usedPassword"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHPasswordChangeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHPasswordChangeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHPasswordChangeResult(/** @type {Partial<SSHPasswordChangeResult>} */($$parsedSource));
    }
}

export class ShellFinding {
    /**
     * Creates a new ShellFinding instance.
     * @param {Partial<ShellFinding>} [$$source = {}] - The source object to create the ShellFinding.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellFinding instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShellFinding}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShellFinding(/** @type {Partial<ShellFinding>} */($$parsedSource));
    }
}

export class SmokeCheckResult {
    /**
     * Creates a new SmokeCheckResult instance.
     * @param {Partial<SmokeCheckResult>} [$$source = {}] - The source object to create the SmokeCheckResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmokeCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SmokeCheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SmokeCheckResult(/** @type {Partial<SmokeCheckResult>} */($$parsedSource));
    }
}

export class SmokeProgressEvent {
    /**
     * Creates a new SmokeProgressEvent instance.
     * @param {Partial<SmokeProgressEvent>} [$$source = {}] - The source object to create the SmokeProgressEvent.
     */
    constructor($$source = {}) {
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["timestamp"] = null;
        }
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["line"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmokeProgressEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SmokeProgressEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SmokeProgressEvent(/** @type {Partial<SmokeProgressEvent>} */($$parsedSource));
    }
}

export class SmokeReport {
    /**
     * Creates a new SmokeReport instance.
     * @param {Partial<SmokeReport>} [$$source = {}] - The source object to create the SmokeReport.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {SmokeCheckResult[]}
             */
            this["results"] = [];
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {SmokeProgressEvent[]}
             */
            this["progress"] = [];
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (!("finishedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["finishedAt"] = null;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("passed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["passed"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SmokeReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SmokeReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        if ("progress" in $$parsedSource) {
            $$parsedSource["progress"] = $$createField1_0($$parsedSource["progress"]);
        }
        return new SmokeReport(/** @type {Partial<SmokeReport>} */($$parsedSource));
    }
}

export class TaskState {
    /**
     * Creates a new TaskState instance.
     * @param {Partial<TaskState>} [$$source = {}] - The source object to create the TaskState.
     */
    constructor($$source = {}) {
        if (!("taskId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskId"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["finishedAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CommandResult[] | undefined}
             */
            this["results"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastError"] = undefined;
        }
        if (!("lastUpdated" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastUpdated"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskState}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField7_0($$parsedSource["results"]);
        }
        return new TaskState(/** @type {Partial<TaskState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RemoteCaptureSession.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RemoteTrafficRecord.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = RemoteFileEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = SSHPasswordChangeResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = SmokeCheckResult.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = SmokeProgressEvent.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = CommandResult.createFrom;
const $$createType13 = $Create.Array($$createType12);
