// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PcapDetail {
    /**
     * Creates a new PcapDetail instance.
     * @param {Partial<PcapDetail>} [$$source = {}] - The source object to create the PcapDetail.
     */
    constructor($$source = {}) {
        if (!("pcapId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pcapId"] = 0;
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("srcIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcIp"] = "";
        }
        if (!("dstIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstIp"] = "";
        }
        if (!("srcPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcPort"] = "";
        }
        if (!("dstPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstPort"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startTime"] = 0;
        }
        if (!("durationSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSec"] = 0;
        }
        if (!("numPackets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numPackets"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("clientContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientContent"] = "";
        }
        if (!("serverContent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PcapDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PcapDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PcapDetail(/** @type {Partial<PcapDetail>} */($$parsedSource));
    }
}
