// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("pcapId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pcapId"] = 0;
        }
        if (!("clientId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["clientId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("srcIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcIp"] = "";
        }
        if (!("dstIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstIp"] = "";
        }
        if (!("srcPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["srcPort"] = "";
        }
        if (!("dstPort" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dstPort"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startTime"] = 0;
        }
        if (!("durationSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSec"] = 0;
        }
        if (!("numPackets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["numPackets"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}
