// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("ownIPs" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ownIPs"] = "";
        }
        if (!("shell" in $$source)) {
            /**
             * @member
             * @type {ShellConfig}
             */
            this["shell"] = (new ShellConfig());
        }
        if (!("ssh" in $$source)) {
            /**
             * @member
             * @type {SSHConfig}
             */
            this["ssh"] = (new SSHConfig());
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {DatabaseConfig}
             */
            this["database"] = (new DatabaseConfig());
        }
        if (!("undeadHorse" in $$source)) {
            /**
             * @member
             * @type {UndeadHorseConfig}
             */
            this["undeadHorse"] = (new UndeadHorseConfig());
        }
        if (!("wormShell" in $$source)) {
            /**
             * @member
             * @type {WormShellConfig}
             */
            this["wormShell"] = (new WormShellConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shell" in $$parsedSource) {
            $$parsedSource["shell"] = $$createField2_0($$parsedSource["shell"]);
        }
        if ("ssh" in $$parsedSource) {
            $$parsedSource["ssh"] = $$createField3_0($$parsedSource["ssh"]);
        }
        if ("database" in $$parsedSource) {
            $$parsedSource["database"] = $$createField4_0($$parsedSource["database"]);
        }
        if ("undeadHorse" in $$parsedSource) {
            $$parsedSource["undeadHorse"] = $$createField5_0($$parsedSource["undeadHorse"]);
        }
        if ("wormShell" in $$parsedSource) {
            $$parsedSource["wormShell"] = $$createField6_0($$parsedSource["wormShell"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class DatabaseConfig {
    /**
     * Creates a new DatabaseConfig instance.
     * @param {Partial<DatabaseConfig>} [$$source = {}] - The source object to create the DatabaseConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseConfig(/** @type {Partial<DatabaseConfig>} */($$parsedSource));
    }
}

export class SSHConfig {
    /**
     * Creates a new SSHConfig instance.
     * @param {Partial<SSHConfig>} [$$source = {}] - The source object to create the SSHConfig.
     */
    constructor($$source = {}) {
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfig(/** @type {Partial<SSHConfig>} */($$parsedSource));
    }
}

export class ShellConfig {
    /**
     * Creates a new ShellConfig instance.
     * @param {Partial<ShellConfig>} [$$source = {}] - The source object to create the ShellConfig.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["port"] = "";
        }
        if (!("pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pass"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["file"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("payload" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["payload"] = "";
        }
        if (!("timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeout"] = 0;
        }
        if (!("proxy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ShellConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShellConfig(/** @type {Partial<ShellConfig>} */($$parsedSource));
    }
}

export class UndeadHorseConfig {
    /**
     * Creates a new UndeadHorseConfig instance.
     * @param {Partial<UndeadHorseConfig>} [$$source = {}] - The source object to create the UndeadHorseConfig.
     */
    constructor($$source = {}) {
        if (!("urlPass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["urlPass"] = "";
        }
        if (!("pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pass"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UndeadHorseConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UndeadHorseConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UndeadHorseConfig(/** @type {Partial<UndeadHorseConfig>} */($$parsedSource));
    }
}

export class WormShellConfig {
    /**
     * Creates a new WormShellConfig instance.
     * @param {Partial<WormShellConfig>} [$$source = {}] - The source object to create the WormShellConfig.
     */
    constructor($$source = {}) {
        if (!("urlPass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["urlPass"] = "";
        }
        if (!("pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pass"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WormShellConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WormShellConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WormShellConfig(/** @type {Partial<WormShellConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ShellConfig.createFrom;
const $$createType1 = SSHConfig.createFrom;
const $$createType2 = DatabaseConfig.createFrom;
const $$createType3 = UndeadHorseConfig.createFrom;
const $$createType4 = WormShellConfig.createFrom;
